import numpy as np
from control_loop import ControlLoop
import sys
sys.path.append('../../duckietown-sim/')
from gym_duckietown.envs import DuckietownEnv

'''
Compute the angle of the line between a position and a goal.
Input:
    goal: [x,y] vector
    pos: [x,y] vector
Output:
    angle: 0-2pi
Might be useful for PID error terms.
'''
def angle_to_goal(goal, pos):
    vec_to_goal = goal - cur_pos
    return np.arctan2(-vec_to_goal[1], vec_to_goal[0]) % (2*np.pi)

'''
ControlLoop PID Implementation
Use PID to compute actions to reach the next waypoint.
State: [x, y, heading angle] (numpy array)
Action: [velocity, steering angle]
'''
class PID(ControlLoop):

    def __init__(self, waypoints, dt, threshold=0.1, debug=False): # Feel free to add more arguments
        ControlLoop.__init__(self, waypoints=waypoints, dt=dt, threshold=threshold, debug=debug)

        ######################################
        #       Initialize PID constants     #
        ######################################

    '''
    Use 2 PID loops (one for throttle, one for steering)
    to compute an action given a state and a goal
      Input: state = [x, y, heading angle]
      Access to self.cur_waypoint = [target_x, target_y]
      Output: action = [throttle, steering]
    Refer to PID_demo in demos/week 8 if you want to reference an example PID loop
    '''
    def calc_action(self, state):
        cur_pos, cur_angle = state[:2], state[2]

        ######################################
        #       Implement PID Algorithm      #
        ######################################
        ''''
        Calculate error:
            2 error terms corresponding to the 2 action dimensions
            the first should be minimized by setting velocity, options include 
              - Distance to next waypoint
              - Just setting a constant velocity instead of using PID
            the second should be minimized by setting steering, options include 
              - Crosstrack error (shortest distance to the path connecting the last and next waypoints)
              - Heading error (difference between current heading and angle to goal)
        Compute PID terms:
            Proportional - constant * error
            Integral - integrate the error over time (by tracking the total error)
            Derivative - find the emperical derivative of error (by tracking the last error)
        Compute action:
            For each error term, compute a weighted sum of the its PID terms.
            Return action = [velocity, steering angle]
        Note: Keeping error, constants, and action as 2-long np vectors will make code neat!
        Make helper functions or instance variables as needed
        '''
        error = None
        action = None

        if self.debug:
            print("State: {}, Waypoint: {}, Action: {}".format(state, self.cur_waypoint, action))
        return action

    def set_waypoint(self, waypoint):
        ControlLoop.set_waypoint(self, waypoint)

        ######################################
        #           Reset PID Loop           #
        ######################################
        '''
        Reset PID terms each time a waypoint is set
        If not reset, derivative term will spike
        '''

    # Make more methods if you wish!

if __name__ == "__main__":
    # Example trajectory, as would be generated by path planning
    trajectory = [np.array([2., 1.]), np.array([2., 3.]), np.array([1., 3.]), np.array([1.,1.])]

    env = DuckietownEnv(map_name='udem1', user_tile_start=(1, 1), init_angle=0, domain_rand=False)
    env.reset()
    env.render(top_down=True)

    # TODO: Pass any args you need
    control_loop = PID(..., waypoints=trajectory, dt=env.delta_time, threshold=0.1, debug=True)

    while not control_loop.is_finished:
        cur_pos = [env.cur_pos[0], env.cur_pos[2]]
        cur_angle = env.cur_angle % (2*np.pi)
        state = cur_pos + [cur_angle]

        action = control_loop.get_action(state)

        env.step(action)
        env.render(top_down=True)

    print("FINISHED")


######################################
#           CHECKOFF                 #
######################################
'''
Send us a screen recording of your PID control loop in action, along with this file (pid.py).
Also send any changes to other files you used, including your Q and R matrices in lqr.py.

Since iLQR is very computationally intensive and as such, difficult to tune in this highly nonlinear environment,
you will not be required to fully follow the trajectory. You should however at least be able see the car moving towards the first waypoint.
4-6 sentences about your process for choosing Q and R and any insights about the algorithm you learned by exploring the code will suffice.
If you do get it running, we'd love to see!
'''
